### ISSUE TITLE
Nothing happens when I try to launch Kingdom Hearts HD

### ISSUE THREAD

**Issue by AsixJin** [KHOmega/KH-PC-and-Linux-Setup#3]
I followed the [KH2 Re:Fined](https://github.com/KHOmega/KH-PC-and-Linux-Setup/blob/main/refined-linux-setup.md) guide twice but once I get to the "[Launching Re:Fined v4.xx.](https://github.com/KHOmega/KH-PC-and-Linux-Setup/blob/main/refined-linux-setup.md#launching-refined-v4xx)" section and try to start up Kingdom Hearts HD 1.5+2.5 ReMIX nothing happens. Heroic says the game is running but nothing happens. I've also noticed and followed the guide since the update about an hour ago.

Here's my log from Heroic if it helps:

```
Launching "KINGDOM HEARTS HD 1.5+2.5 ReMIX" (legendary)
Native? No
Installed in: /home/deck/Games/Heroic/KH_1.5_2.5

System Info:
CPU: 8x AMD Custom APU 0405
Memory: 15.54 GB (used: 3.74 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] VanGogh [AMD Custom GPU 0405]
    IDs: D=163f V=1002 SD=0123 SV=1002
    Driver: amdgpu
OS: SteamOS 3.4.8 holo (linux)

The current system is a Steam Deck (model: LCD) in desktop mode
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.12.1 Vegapunk
  Legendary: 0.20.34 Direct Intervention
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

Game Settings: {
	"autoInstallDxvk": true,
	"autoInstallVkd3d": true,
	"preferSystemLibs": false,
	"enableEsync": true,
	"enableFsync": true,
	"nvidiaPrime": false,
	"offlineMode": false,
	"enviromentOptions": [],
	"wrapperOptions": [],
	"showFps": false,
	"targetExe": "",
	"useGameMode": true,
	"language": "",
	"wineVersion": {
		"bin": "/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-25/bin/wine",
		"name": "Wine - Wine-GE-Proton8-25",
		"type": "wine",
		"lib": "/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-25/lib64",
		"lib32": "/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-25/lib",
		"wineserver": "/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-25/bin/wineserver"
	},
	"winePrefix": "/home/deck/Games/Heroic/Prefixes/default/KINGDOM HEARTS HD 1.52.5 ReMIX",
	"wineCrossoverBottle": "",
	"ignoreGameUpdates": false
}

Game launched at: Sat Feb 10 2024 19:14:38 GMT-0500 (Eastern Standard Time)

Launch Command: LD_LIBRARY_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-25/lib64:/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-25/lib:/usr/lib/extensions/vulkan/gamescope/lib HEROIC_APP_NAME=68c214c58f694ae88c2dab6f209b43e4 HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic LD_PRELOAD= DOTNET_BUNDLE_EXTRACT_BASE_DIR= DOTNET_ROOT= WINEPREFIX="/home/deck/Games/Heroic/Prefixes/default/KINGDOM HEARTS HD 1.52.5 ReMIX" WINEDLLOVERRIDES=winemenubuilder.exe=d WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEFSYNC=1 ORIG_LD_LIBRARY_PATH=/usr/lib/extensions/vulkan/gamescope/lib GST_PLUGIN_SYSTEM_PATH_1_0=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-25/lib64/gstreamer-1.0:/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-25/lib/gstreamer-1.0 WINEDLLPATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-25/lib64/wine:/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-25/lib/wine /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch 68c214c58f694ae88c2dab6f209b43e4 --wine /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-25/bin/wine --wrapper /app/bin/gamemoderun --language en

Game Log:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching 68c214c58f694ae88c2dab6f209b43e4...
gamemodeauto: 
gamemodeauto: 
wine: using kernel write watches (experimental).
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
wine: using kernel write watches (experimental).
002c:fixme:winediag:LdrInitializeThunk wine-staging 8.0 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0094:err:hid:udev_bus_init UDEV monitor creation failed
009c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:err:wineusb:DriverEntry Failed to initialize Unix library, status 0xc0000135.
0080:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000135
009c:fixme:xinput:pdo_pnp IRP_MN_QUERY_ID type 5, not implemented!
0034:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 126
009c:fixme:xinput:pdo_pnp IRP_MN_QUERY_ID type 5, not implemented!
009c:fixme:xinput:pdo_pnp IRP_MN_QUERY_ID type 5, not implemented!
009c:fixme:xinput:pdo_pnp IRP_MN_QUERY_ID type 5, not implemented!
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
```

**Comment by AsixJin** [comment]
After doing some troubleshooting I realized it only hangs when "version.dll" (or VERSION.DLL) is in the game's directory and/or if it's listed under "libraries" in winecfg. If it's removed the games with run but I get a "404 re:fined patch not found" error for KH2.

I assume this "version.dll" is needed but I'm not sure where it's coming from (its not in the KH Re:fined zip). I also noticed in your guide you say to enter "VERSION.DLL" but the text field in the winecfg's libraries doesn't except captial characters. Could that be an issue?

**Comment by KHOmega** [comment]
> After doing some troubleshooting I realized it only hangs when "version.dll" (or VERSION.DLL) is in the game's directory and/or if it's listed under "libraries" in winecfg. If it's removed the games with run but I get a "404 re:fined patch not found" error for KH2.
> 
> I assume this "version.dll" is needed but I'm not sure where it's coming from (its not in the KH Re:fined zip). I also noticed in your guide you say to enter "VERSION.DLL" but the text field in the winecfg's libraries doesn't except captial characters. Could that be an issue?

`version.dll` is needed for Panacea to function in OpenKH. Without it, Re:Fined won't load correctly.

In the guide, the following is stated:
![image](https://github.com/KHOmega/KH-PC-and-Linux-Setup/assets/93887977/a13e7a47-de12-46d1-887c-a2df05ab94a7)

This creates `version.dll` in your game directory.

winecfg's libraries are not case-sensitive.

**Comment by AsixJin** [comment]
Okay! After another day of troubleshooting, I found the issue. I'm not sure why this was in my case but Re:Fined was looking for and/or trying to create the `4d5ebce2bb284c25b3aa670612feea83` folder within the Config and Save folders (the ones found in the `Kingdom Hearts` folder in the Documents folder) and was unable to do so causing it to not start.

Creating the `4d5ebce2bb284c25b3aa670612feea83` folder in both directories manually seemed to do the trick and Re:Fined was able to start. I only found this out after downgrading to 4.17, which was able to create the folders needed presumably and start, and then upgrading back to 4.55. I downgraded to 4.20 but it would also not start, presumably because it couldn't create the folders either. 

I installed Re:Fined on my Windows computer and ran into the same issue with the same fix. I'm not sure if I did anything wrong following the guides but I thought I'd at least explain what happened and how I fixed it in case it helps someone else, but most importantly I got it running. Thank you for the help and guides.

**Comment by KHOmega** [comment]
> Okay! After another day of troubleshooting, I found the issue. I'm not sure why this was in my case but Re:Fined was looking for and/or trying to create the `4d5ebce2bb284c25b3aa670612feea83` folder within the Config and Save folders (the ones found in the `Kingdom Hearts` folder in the Documents folder) and was unable to do so causing it to not start.
> 
> Creating the `4d5ebce2bb284c25b3aa670612feea83` folder in both directories manually seemed to do the trick and Re:Fined was able to start. I only found this out after downgrading to 4.17, which was able to create the folders needed presumably and start, and then upgrading back to 4.55. I downgraded to 4.20 but it would also not start, presumably because it couldn't create the folders either.
> 
> I installed Re:Fined on my Windows computer and ran into the same issue with the same fix. I'm not sure if I did anything wrong following the guides but I thought I'd at least explain what happened and how I fixed it in case it helps someone else, but most importantly I got it running. Thank you for the help and guides.

I usually only see this issue on Windows, as that string of text is your EPIC ID.

I'll note this for future use!
