### ISSUE TITLE
Problem installing dotnet

### ISSUE THREAD

**Issue by GiuseppeLaurenza** [KHOmega/KH-PC-and-Linux-Setup#4]
Clean SteamOS installation.
Make all the update, install from discovery store HeroicLauncher
I am at the phase of install dotnet 4.8, but i ended at "error User selected 'Cancel'" and the game do not start. How is it possible to install dotnet and make games working?

**Comment by KHOmega** [comment]
Please restart your device and re-creating the prefix and installing dotnet48 again.
